import Footer from "@/components/Footer";

import UserNavbar from "@/components/Navbars/UserNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "User | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <UserNavbar />
      {children}
      <Footer />
    </div>
  );
}
